### ISSUE TITLE
[Feature Request] Add options for clock-in and clock-out

### ISSUE THREAD

**Issue by EricDriussi** [DanielRamosAcosta/factorial-cli#12]
Hi there!
I think it would be pretty cool if, on top of the current functionality, a user could run something like `factorial clock-in` and `factorial clock-out` to start a shift or end it from the cli.

This would make it easy to script this behavior (think something silly like start a shift when the PC is turned on or end it when powered off).

Do you think this is doable/desirable? Are you open to PRs? 
I'm not familiar with Factorial's API but I might be able to give it a try (although not sure when).

**Comment by DanielRamosAcosta** [comment]
I think this is doable yes! But I have little time for this. PR's always welcome @EricDriussi :)

**Comment by DanielRamosAcosta** [comment]
Closing because time has passed 😝
