### ISSUE TITLE
Issue when installing with deno command

### ISSUE THREAD

**Issue by EricDriussi** [DanielRamosAcosta/factorial-cli#5]
Hi there!

I'm getting this error when trying to install:
```
error: TS2339 [ERROR]: Property 'getIterator' does not exist on type 'ReadableStream<R>'.
  return res.readable.getIterator();
```

This happens when I run `deno install --allow-env --allow-net https://raw.githubusercontent.com/DanielRamosAcosta/factorial-cli/main/src/factorial.ts` (the command included in the readme).

I've tried it both with and without `--allow-env`, as well as including my credentials in an `.env` file copied from `.env.example`.

I'll try to fix the issue and make a PR as soon as I have the time, just thought I'd leave it here in case there's a trivial solution I'm missing :smiley: 

Keep up the good work! :mechanical_arm:

**Comment by DanielRamosAcosta** [comment]
Which Deno version are you using @EricDriussi?

**Comment by DanielRamosAcosta** [comment]
I think that deno website is down: https://deno.land

**Comment by EricDriussi** [comment]
The issue still persists but if I clone the project and then run `deno install --allow-env --allow-net src/factorial.ts` from the root dir it works just fine :smile: maybe an issue with the URL? :thinking: 

Oh btw, `deno --version` outputs this:
```
deno 1.16.0 (release, x86_64-unknown-linux-gnu)
v8 9.7.106.2
typescript 4.4.2
```

**Comment by DanielRamosAcosta** [comment]
Strange, needs more investigation

**Comment by DanielRamosAcosta** [comment]
@EricDriussi `cache -r https://raw.githubusercontent.com/DanielRamosAcosta/factorial-cli/main/src/factorial.ts` worked for me, and then the install script.
